name: orcamento_pedreiro
description: "Aplicativo destinado a criar orçamento de pedreiro"

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  intl: ^0.19.0
  pdf: ^3.10.4
  path_provider: ^2.1.1
  open_file: ^3.3.2
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - imagens/

  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
